# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2abccba8e8403284f0e1b28ead5b5cab6b4a3e3a3310c0b80f0848d9bb5dd70821bd652bdf063222d7971cc2ef652d58be61c4fcb68c76eac7f9d2d7aca6725

test:
  secret_key_base: a5a153eb710a8907871b72666965b21d12ae5d8a9761ad42e65d1c94e42ba2f5023770af1a9f594a82a1079afedb178b96c70302080cb6ab6c62d9a90cea4b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
